wandb_version: 1

learning_rate:
  desc: null
  value: 0.05
backbone_class:
  desc: null
  value: densenet161
dataset:
  desc: null
  value: soybean_2_1
Max epochs:
  desc: null
  value: 3
Segmentation Training:
  desc: null
  value: true
Classification Training:
  desc: null
  value: false
freeze_all:
  desc: null
  value: true
manet:
  desc: null
  value: false
mmanet:
  desc: null
  value: true
maskguided:
  desc: null
  value: false
unet:
  desc: null
  value: true
transfer_to:
  desc: null
  value: 0.0
fsds:
  desc: null
  value: false
local_train:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705692203.837344
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 16
      - 19
      - 23
      4: 3.10.5
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
deconv_3_no_ch:
  desc: null
  value: 0.125
deconv_5_no_ch:
  desc: null
  value: 0.0625
atrous_2_no_ch:
  desc: null
  value: 0.25
atrous_3_no_ch:
  desc: null
  value: 0.25
max_mean_no_ch:
  desc: null
  value: 0.125
model_no_paras:
  desc: null
  value: 438.263116
